/* Generated by scripts/build-glb-script.mjs - do not edit by hand.
   Embedded copy of public/models/campus.glb (gzip level 9 in base64, 96.5 MB from 329.5 MB).
   sha256 99951c34218c5a4a03a870637b7a4a3267e29ba081dc66fa05f204bebe9c28b4
   Classic script because file:// blocks fetch and XHR. */
window.__HEPU_GLB_META__={binary:'campus.glb',encoding:'gzip-base64',bytes:345456788,packed:101151431,sha256:'99951c34218c5a4a03a870637b7a4a3267e29ba081dc66fa05f204bebe9c28b4',parts:[{"file":"campus.glb.gz.part-0.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-1.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-2.js","bytes":34207352,"characters":34205280}]};
window.__HEPU_GLB__campus=
[]
;
