/* Generated by scripts/build-glb-script.mjs - do not edit by hand.
   Embedded copy of public/models/campus.glb (gzip level 9 in base64, 98.0 MB from 348.1 MB).
   sha256 cdac1cdff727aca605dd58b74fad9e2ecabb5e873743321a55e61dc1dc6afac0
   Classic script because file:// blocks fetch and XHR. */
window.__HEPU_GLB_META__={binary:'campus.glb',encoding:'gzip-base64',bytes:364985460,packed:102748751,sha256:'cdac1cdff727aca605dd58b74fad9e2ecabb5e873743321a55e61dc1dc6afac0',parts:[{"file":"campus.glb.gz.part-0.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-1.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-2.js","bytes":36337220,"characters":36335040}]};
window.__HEPU_GLB__campus=
[]
;
