/* Generated by scripts/build-glb-script.mjs - do not edit by hand.
   Embedded copy of public/models/campus.glb (gzip level 9 in base64, 96.1 MB from 334.2 MB).
   sha256 35a23a7c0416fd8230af98631641d2a10fd5d7e7b922257907fd008ba6af5187
   Classic script because file:// blocks fetch and XHR. */
window.__HEPU_GLB_META__={binary:'campus.glb',encoding:'gzip-base64',bytes:350450636,packed:100788684,sha256:'35a23a7c0416fd8230af98631641d2a10fd5d7e7b922257907fd008ba6af5187',parts:[{"file":"campus.glb.gz.part-0.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-1.js","bytes":50334548,"characters":50331648},{"file":"campus.glb.gz.part-2.js","bytes":33723664,"characters":33721616}]};
window.__HEPU_GLB__campus=
[]
;
